### ISSUE TITLE
Export precision 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/tuning-library#61]
<@609578720419905575> , <@256888540917399553> reported:
> Checked the scala export. Floating point values near zero are being truncated to integers
> And Scala interprets integers as harmonics
We're using the SST Tuning lib - is this expected behaviour?

**Comment by SingABrightSong** [comment]
Hi, I'm the person who found this when testing Entonal Studio. The issue is specifically that the Tuning Library strips the decimal point from cent values when rounding. A tuning such as 12tet, which has perfectly round cent values by definition, will be exported without the decimal point. As the decimal point is what the Scala format uses to distinguish cents from rational intervals, the 100 cent integers of 12edo are thus parsed as fractions over 1, i.e. integer harmonics.
![image](https://user-images.githubusercontent.com/1489009/179744101-f1eacb7f-fe70-4efa-a37e-395a8506f3dc.png)

**Comment by baconpaul** [comment]
OK so we found out that this doesn't happen for scales which are generated by the tuning library or scales that are imported from files. This is happening for scales generated by entonal. So now we need to figure out how entonal is generating the SCL files. (And add that as a test case or feature set to tuning lib)

**Comment by baconpaul** [comment]
Turns out this is an entonal bug
